version: "3.8"

services:
  revacc:
    image: umeshdahiya01/revacc:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - MEV_STEP_TICK_MS=650
      - MEV_CORS_ORIGINS=*
    container_name: revacc-pipeline
    restart: unless-stopped
