"""Task 20.6 local adversarial tests for guarded official PDB qualification.

Every response is generated by an in-process ``httpx.MockTransport``.  No
request contacts SWISS-MODEL, and local PDB fixtures are created from amino-acid
letters rather than copied provider payloads.
"""
from __future__ import annotations

from datetime import datetime, timezone
import secrets

import httpx
import pytest

from app.tools.swissmodel_contract import OfficialAutomodelReceipt
from app.tools.swissmodel_resilience import (
    OfficialSwissModelCoreApiHttpTransport,
    OfficialSwissModelCoreApiRoutes,
    OfficialSwissModelModelSummary,
    OfficialSwissModelProject,
    SwissModelLifecycleOutcome,
    SwissModelPdbDownloadError,
    SwissModelResilientLifecycle,
    SwissModelRetryPolicy,
    _OFFICIAL_PDB_MAX_BYTES,
)
from app.tools.swissmodel_runtime import preflight_swissmodel_submission

from .swissmodel_contract_fixtures import (
    assert_public_sinks_safe,
    completed_step_9_2_mev,
    exact_mev_pdb,
)


class _Decoder:
    """Local decoder stand-in; no provider response fields leave transport scope."""

    def automodel_receipt(self, _payload: object) -> OfficialAutomodelReceipt:
        return OfficialAutomodelReceipt()

    def project(self, _payload: object) -> OfficialSwissModelProject:
        return OfficialSwissModelProject(state="queued")

    def project_model_summary(self, _payload: object) -> OfficialSwissModelModelSummary:
        return OfficialSwissModelModelSummary()


def _routes(
    *,
    model_pdb_url=None,
) -> OfficialSwissModelCoreApiRoutes:
    return OfficialSwissModelCoreApiRoutes(
        automodel_url="https://swissmodel.expasy.org/automodel/",
        project_url=lambda project_id: f"https://swissmodel.expasy.org/project/{project_id}/",
        project_models_summary_url=(
            lambda project_id: f"https://swissmodel.expasy.org/project/{project_id}/models/"
        ),
        model_pdb_url=(
            model_pdb_url
            or (
                lambda project_id, model_id:
                f"https://swissmodel.expasy.org/project/{project_id}/model/{model_id}/pdb/"
            )
        ),
    )


def _core_transport(
    monkeypatch: pytest.MonkeyPatch,
    handler,
    *,
    routes: OfficialSwissModelCoreApiRoutes | None = None,
) -> OfficialSwissModelCoreApiHttpTransport:
    # This generated value stays only in the process environment and request
    # construction; no fixture or assertion serializes it.
    monkeypatch.setenv("SWISSMODEL_API_TOKEN", secrets.token_urlsafe(32))
    return OfficialSwissModelCoreApiHttpTransport(
        routes=routes or _routes(),
        decoder=_Decoder(),
        policy=SwissModelRetryPolicy(
            connect_timeout_seconds=1.0,
            read_timeout_seconds=1.0,
            overall_timeout_seconds=2.0,
        ),
        http_transport=httpx.MockTransport(handler),
    )


def _pdb_response(pdb_text: str) -> httpx.Response:
    return httpx.Response(
        200,
        headers={"Content-Type": "chemical/x-pdb"},
        content=pdb_text.encode("utf-8"),
    )


@pytest.mark.asyncio
async def test_valid_exact_official_pdb_is_qualified_with_safe_provenance(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A complete local PDB succeeds only after the existing exact validator runs."""
    pdb_text = exact_mev_pdb("AVLG")
    requested_urls: list[str] = []

    async def handler(request: httpx.Request) -> httpx.Response:
        requested_urls.append(str(request.url))
        return _pdb_response(pdb_text)

    transport = _core_transport(monkeypatch, handler)
    qualified = await transport.qualify_model_pdb(
        project_id="project-42",
        model_id="model-7",
        expected_sequence="AVLG",
    )

    assert requested_urls == [
        "https://swissmodel.expasy.org/project/project-42/model/model-7/pdb/"
    ]
    assert qualified.sequence_identity_validation["identityPercent"] == 100.0
    assert qualified.sequence_identity_validation["coveragePercent"] == 100.0
    assert qualified.transient_structure_input()["coordinateText"] == pdb_text
    public = qualified.public_provenance()
    assert public["modelUrl"] == requested_urls[0]
    assert "coordinateText" not in public
    assert_public_sinks_safe(public, transient_coordinate_text=pdb_text)


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "location",
    (
        "http://swissmodel.expasy.org/project/project-42/model/model-7/pdb/",
        "https://127.0.0.1/private-model/",
        "https://user:pass@swissmodel.expasy.org/project/project-42/model/model-7/pdb/",
    ),
)
async def test_redirects_to_non_https_private_or_credential_urls_are_rejected(
    monkeypatch: pytest.MonkeyPatch,
    location: str,
) -> None:
    """Unsafe redirect targets never receive a follow-up request."""
    requested_urls: list[str] = []

    async def handler(request: httpx.Request) -> httpx.Response:
        requested_urls.append(str(request.url))
        return httpx.Response(302, headers={"Location": location})

    transport = _core_transport(monkeypatch, handler)
    with pytest.raises(SwissModelPdbDownloadError) as rejected:
        await transport.qualify_model_pdb(
            project_id="project-42",
            model_id="model-7",
            expected_sequence="AVLG",
        )

    assert rejected.value.code == "pdb_redirect_invalid"
    assert requested_urls == [
        "https://swissmodel.expasy.org/project/project-42/model/model-7/pdb/"
    ]


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "unsafe_url",
    (
        "http://swissmodel.expasy.org/project/project-42/model/model-7/pdb/",
        "https://127.0.0.1/project/project-42/model/model-7/pdb/",
        "https://user:pass@swissmodel.expasy.org/project/project-42/model/model-7/pdb/",
    ),
)
async def test_malicious_provider_pdb_routes_are_rejected_before_network_access(
    monkeypatch: pytest.MonkeyPatch,
    unsafe_url: str,
) -> None:
    """The route itself must be official HTTPS before any model request is sent."""
    calls = 0

    async def handler(_request: httpx.Request) -> httpx.Response:
        nonlocal calls
        calls += 1
        return _pdb_response(exact_mev_pdb("AVLG"))

    transport = _core_transport(
        monkeypatch,
        handler,
        routes=_routes(model_pdb_url=lambda _project_id, _model_id: unsafe_url),
    )
    with pytest.raises(ValueError, match="official CoreAPI URL"):
        await transport.read_model_pdb(project_id="project-42", model_id="model-7")

    assert calls == 0


@pytest.mark.asyncio
async def test_pdb_route_must_include_the_recorded_project_and_model_identifiers(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A model ID alone cannot construct a provider-approved PDB route."""
    calls = 0

    async def handler(_request: httpx.Request) -> httpx.Response:
        nonlocal calls
        calls += 1
        return _pdb_response(exact_mev_pdb("AVLG"))

    transport = _core_transport(
        monkeypatch,
        handler,
        routes=_routes(
            model_pdb_url=lambda _project_id, model_id:
            f"https://swissmodel.expasy.org/model/{model_id}/pdb/"
        ),
    )
    with pytest.raises(ValueError, match="project identifier"):
        await transport.read_model_pdb(project_id="project-42", model_id="model-7")

    assert calls == 0


@pytest.mark.asyncio
@pytest.mark.parametrize(
    ("pdb_text", "expected_code"),
    (
        ("HEADER local-invalid\nEND\n", "pdb_exact_validation_failed"),
        (exact_mev_pdb("AVLA"), "pdb_exact_validation_failed"),
        (exact_mev_pdb("AVL"), "pdb_exact_validation_failed"),
    ),
)
async def test_malformed_mismatched_or_missing_coordinate_pdbs_are_rejected(
    monkeypatch: pytest.MonkeyPatch,
    pdb_text: str,
    expected_code: str,
) -> None:
    """Malformed data, a wrong sequence, and absent required residues cannot qualify."""

    async def handler(_request: httpx.Request) -> httpx.Response:
        return _pdb_response(pdb_text)

    transport = _core_transport(monkeypatch, handler)
    with pytest.raises(SwissModelPdbDownloadError) as rejected:
        await transport.qualify_model_pdb(
            project_id="project-42",
            model_id="model-7",
            expected_sequence="AVLG",
        )

    assert rejected.value.code == expected_code


@pytest.mark.asyncio
async def test_partial_c_alpha_coverage_is_rejected_even_when_residue_records_remain(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A residue without its required C-alpha cannot be hidden by other atom records."""
    full_pdb = exact_mev_pdb("AVLG")
    partial_pdb = "\n".join(
        line
        for line in full_pdb.splitlines()
        if not (line.startswith("ATOM") and line[12:16].strip() == "CA" and line[22:26].strip() == "3")
    ) + "\n"

    async def handler(_request: httpx.Request) -> httpx.Response:
        return _pdb_response(partial_pdb)

    transport = _core_transport(monkeypatch, handler)
    with pytest.raises(SwissModelPdbDownloadError) as rejected:
        await transport.qualify_model_pdb(
            project_id="project-42",
            model_id="model-7",
            expected_sequence="AVLG",
        )

    assert rejected.value.code == "pdb_exact_validation_failed"


@pytest.mark.asyncio
async def test_non_pdb_content_type_is_rejected_before_parse(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A response must declare an allowed PDB MIME type before its body is read."""

    async def handler(_request: httpx.Request) -> httpx.Response:
        return httpx.Response(
            200,
            headers={"Content-Type": "text/plain"},
            content=b"local-non-pdb",
        )

    transport = _core_transport(monkeypatch, handler)
    with pytest.raises(SwissModelPdbDownloadError) as rejected:
        await transport.read_model_pdb(project_id="project-42", model_id="model-7")

    assert rejected.value.code == "pdb_content_type_invalid"


@pytest.mark.asyncio
async def test_oversized_pdb_response_is_rejected_from_declared_size(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The size limit is enforced before a declared oversized response is consumed."""

    async def handler(_request: httpx.Request) -> httpx.Response:
        return httpx.Response(
            200,
            headers={
                "Content-Type": "chemical/x-pdb",
                "Content-Length": str(_OFFICIAL_PDB_MAX_BYTES + 1),
            },
            content=b"",
        )

    transport = _core_transport(monkeypatch, handler)
    with pytest.raises(SwissModelPdbDownloadError) as rejected:
        await transport.read_model_pdb(project_id="project-42", model_id="model-7")

    assert rejected.value.code == "pdb_response_too_large"


class _SucceededLifecycleTransport:
    """Local lifecycle fake that reports a completed provider project."""

    def __init__(self) -> None:
        self.create_calls: list[str] = []

    async def create_automodel(self, *, target_sequences: str) -> OfficialAutomodelReceipt:
        self.create_calls.append(target_sequences)
        return OfficialAutomodelReceipt(
            request_id="project-42",
            model_id="model-7",
            model_url="https://swissmodel.expasy.org/project/project-42/model/model-7/pdb/",
            submitted_at=datetime(2025, 1, 2, tzinfo=timezone.utc),
        )

    async def read_project(self, *, project_id: str) -> OfficialSwissModelProject:
        assert project_id == "project-42"
        return OfficialSwissModelProject(state="succeeded")

    async def read_project_model_summary(
        self,
        *,
        project_id: str,
    ) -> OfficialSwissModelModelSummary:
        assert project_id == "project-42"
        return OfficialSwissModelModelSummary(
            model_id="model-7",
            model_url="https://swissmodel.expasy.org/project/project-42/model/model-7/pdb/",
        )


async def _no_sleep(_seconds: float) -> None:
    """Keep local retry-free lifecycle tests deterministic."""


@pytest.mark.asyncio
async def test_only_exact_qualified_coordinates_can_make_lifecycle_succeeded(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A terminal provider state becomes succeeded only with transient exact PDB data."""
    mev = completed_step_9_2_mev()
    pdb_text = exact_mev_pdb(mev.normalized_sequence)

    async def handler(_request: httpx.Request) -> httpx.Response:
        return _pdb_response(pdb_text)

    pdb_transport = _core_transport(monkeypatch, handler)
    preflight = preflight_swissmodel_submission(
        step_9_2_completed=True,
        step_9_2_sequence=mev.raw_sequence,
        current_mev_sequence=mev.normalized_sequence,
        current_mev_fingerprint=mev.fingerprint,
    )
    lifecycle_transport = _SucceededLifecycleTransport()
    lifecycle = SwissModelResilientLifecycle(
        lifecycle_transport,
        pdb_transport=pdb_transport,
        sleep=_no_sleep,
    )

    queued = await lifecycle.create_or_resume(preflight)
    succeeded: SwissModelLifecycleOutcome = await lifecycle.create_or_resume(preflight)

    assert queued.status.state == "queued"
    assert succeeded.status.state == "succeeded"
    assert succeeded.status.pdb_qualified is True
    assert succeeded.qualified_pdb is not None
    assert lifecycle_transport.create_calls == [mev.normalized_sequence]
    persisted = succeeded.persisted_record()
    assert persisted is not None
    assert "coordinateText" not in str(persisted)
    assert_public_sinks_safe(
        succeeded.public_result(),
        persisted,
        transient_coordinate_text=pdb_text,
    )


@pytest.mark.asyncio
async def test_rejected_official_pdb_pauses_without_structure_metrics(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A failed qualification creates neither a success state nor transient metric handoff."""
    mev = completed_step_9_2_mev()

    async def handler(_request: httpx.Request) -> httpx.Response:
        return _pdb_response(exact_mev_pdb("AVLA"))

    pdb_transport = _core_transport(monkeypatch, handler)
    preflight = preflight_swissmodel_submission(
        step_9_2_completed=True,
        step_9_2_sequence=mev.raw_sequence,
        current_mev_sequence=mev.normalized_sequence,
        current_mev_fingerprint=mev.fingerprint,
    )
    lifecycle = SwissModelResilientLifecycle(
        _SucceededLifecycleTransport(),
        pdb_transport=pdb_transport,
        sleep=_no_sleep,
    )

    await lifecycle.create_or_resume(preflight)
    paused = await lifecycle.create_or_resume(preflight)

    assert paused.status.state == "paused"
    assert paused.status.message_code == "swissmodel_pdb_qualification_failed"
    assert paused.status.pdb_qualified is False
    assert paused.qualified_pdb is None
    assert "pdbQualified" not in paused.public_result()
    assert_public_sinks_safe(paused.public_result(), paused.persisted_record())
